<a href="https://colab.research.google.com/github/dacluan94066/THDeeplearning/blob/main/THDeepLearning_Tuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install numpy
import numpy as np

In [3]:
#cau1,2
a = np.random.randint(20, size=(3,3))
print(a)
result = np.all(a)
print("Kiểm tra tất cả các phần tử trong mảng khác 0",result)
print(" kiểm tra tồn tại một phần tử trong mảng khác 0 ",np.any(a))

[[ 8 11 19]
 [ 9 11 17]
 [ 8  2 18]]
Kiểm tra tất cả các phần tử trong mảng khác 0 True
 kiểm tra tồn tại một phần tử trong mảng khác 0  True


In [4]:
# cau3:
#1 chieu

c_1d = np.random.randint(20, size=5)
c_1e = a = np.random.randint(20, size=5)

print("a:", c_1d)
print("b:", c_1e)
print("Greater:", np.greater(c_1d, c_1e))
print("Greater Equal:", np.greater_equal(c_1d, c_1e))
print("Less:", np.less(c_1d, c_1e))
print("Less Equal:", np.less_equal(c_1d, c_1e))

#2 chieu
a_2d = np.random.randint(20, size=(3,3))
b_2d = np.random.randint(20, size=(3,3))
print("a:\n", a_2d)
print("b:\n", b_2d)
print("Greater:\n", np.greater(a_2d, b_2d))
print("Greater Equal:\n", np.greater_equal(a_2d, b_2d))
print("Less:\n", np.less(a_2d, b_2d))
print("Less Equal:\n", np.less_equal(a_2d, b_2d))

a: [10 17 17  1  1]
b: [ 0 18  1  6  4]
Greater: [ True False  True False False]
Greater Equal: [ True False  True False False]
Less: [False  True False  True  True]
Less Equal: [False  True False  True  True]
a:
 [[ 1 15  9]
 [ 2 16  7]
 [15  2 12]]
b:
 [[ 9 14 19]
 [15  2  7]
 [12 11 12]]
Greater:
 [[False  True False]
 [False  True False]
 [ True False False]]
Greater Equal:
 [[False  True False]
 [False  True  True]
 [ True False  True]]
Less:
 [[ True False  True]
 [ True False False]
 [False  True False]]
Less Equal:
 [[ True False  True]
 [ True False  True]
 [False  True  True]]


In [5]:
#cau4
ones = np.full(10,1)
zeros = np.full(10,0)
fives = np.full(10, 5)

print(ones)
print(zeros)
print(fives)



[1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0]
[5 5 5 5 5 5 5 5 5 5]


In [6]:
#cau5
even_array = np.arange(30, 71, 2)
print("Mảng các số nguyên chẵn từ 30 đến 70:")
print(even_array)

Mảng các số nguyên chẵn từ 30 đến 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [7]:
# cau6:
identity_matrix = np.identity(3)
print("Ma trận đơn vị 3x3:")
print(identity_matrix)


Ma trận đơn vị 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# cau7
a_range = np.random.randint(15, 55, size=(20))
print("Mảng gốc:", a_range)

# In các giá trị ngoại trừ phần tử đầu và cuối
print("Các giá trị ngoại trừ phần tử đầu và cuối:")
print(a_range[1:-1])

Mảng gốc: [49 18 31 21 45 48 21 50 23 17 34 51 51 33 24 54 39 33 24 15]
Các giá trị ngoại trừ phần tử đầu và cuối:
[18 31 21 45 48 21 50 23 17 34 51 51 33 24 54 39 33 24]


In [9]:
# cau8:
rd_array = np.random.randint(0, 21, size=20)
print("Mảng gốc:", rd_array)


condition = (rd_array >= 9) & (rd_array <= 15)

modified_array = rd_array.copy()
modified_array[condition] = -modified_array[condition]

print("Mảng sau khi đổi dấu:", modified_array)


Mảng gốc: [ 5 12  4  7 16  2 12  9 14 11  5  2  7 12  7 20  0 20  3 13]
Mảng sau khi đổi dấu: [  5 -12   4   7  16   2 -12  -9 -14 -11   5   2   7 -12   7  20   0  20
   3 -13]


In [10]:
#cau9
rdd_array = np.random.randint(20, size=(3,4))
print(rdd_array)

[[ 3 10  8  0]
 [ 9  0 16  8]
 [ 4 12  2 13]]


In [11]:
#cau10
matrix = np.zeros((10, 10), dtype=int)
matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1

print("Ma trận 10x10 với biên là 1, bên trong là 0:")
print(matrix)

Ma trận 10x10 với biên là 1, bên trong là 0:
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]
